# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TerraAntiqua
                                 A QGIS plugin
 The plugin creates a paleoDEM by combining present day topography and paleobathimetry, and modiying the final topography by introducing masks.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-03-18
        copyright            : (C) 2021 by Jovid Aminov and Diego Ruiz
        email                : jovid.aminov@outlook.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Loads TerraAntiqua, falling back to TerraAntiquaStub if deps are missing.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    try:
        from .core.terra_antiqua import TerraAntiqua
        from .core.cache_manager import cache_manager
        cache_manager.start_background_init()
        return TerraAntiqua(iface)
    except Exception:
        from .core.terra_antiqua_stub import TerraAntiquaStub
        return TerraAntiquaStub(iface)
