channels:
  - conda-forge
dependencies:
  - python=3.12
  - appdirs
  - gmt
  - qgis
  - gplately
  - pygplates
  - plate-model-manager
  - pip
  - pip:
    - PlateTectonicTools
    - paleo-age-grids
